databases:
  - name: control-horario-db
    plan: free
    databaseName: control_horario
    user: control_horario

services:
  - type: web
    name: control-horario-backend
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: control-horario-db
          property: connectionString
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRES
        value: 15m
      - key: JWT_REFRESH_EXPIRES
        value: 7d
      - key: PORT
        value: 3001
      - key: CORS_ORIGIN
        value: https://control-horario-frontend-p3ix.onrender.com

  - type: web
    name: control-horario-frontend
    runtime: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://control-horario-backend-kwfa.onrender.com/api
      - key: HOSTNAME
        value: 0.0.0.0
